# *Neural Network*
## 4. 3층 신경망 구현하기

> - NumPy 배열을 활용하여 적은 코드만으로 아래의 신경망 구현
![](image/fig 3-15.png)

___

### 1) 표기법 설명


- 이번 절에서는 $w_{12}^{(1)}나 a_1^{(1)}$ 같은 표기법 등장

![](image/fig 3-16.png)

- $w_{12}^{(1)}$를 풀어 설명하면 다음과 같음
- 0번 층의 2번째 뉴런 $x_2$에서, 1번 층의 1번째 뉴런 $a_1$으로 향할 때의 가중치

___

### 2) 각 층의 신호 전달 구현하기

- '1층의 첫번째 뉴런으로 가는 신호'
- 편향 뉴런이 추가됨
![](image/fig 3-17.png)

- $a_1^{(1)}$는 가중치를 곱한 신호 두개와 편향을 합해서 계산
$$
a_1^{(1)} = w_{11}^{(1)}x_1 + w_{12}^{(1)}x_2 + b_1^{(1)}$$

- 행렬 곱으로 표현시 다음과 같이 간소화 가능

$$
A^{(1)} = XW^{(1)} + B^{(1)}
$$

$$ A^{(1)} = (a_1^{(1)}, a_2^{(1)}, a_3^{(1)}),\quad X = (x_1, x_2), \quad B^{(1)} = (b_1^{(1)},b_2^{(1)}, b_3^{(1)})\\
W^{(1)} = \begin{bmatrix}w_{11}^{(1)} & w_{21}^{(1)} & w_{31}^{(1)}\\w_{12}^{(1)} & w_{22}^{(1)} & w_{32}^{(1)}\end{bmatrix}$$


In [3]:
X = np.array([1, 0.5])
W1 = np.array([[0.1 , 0.3, 0.5], [0.2 , 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1

(2, 3)
(2,)
(3,)


In [4]:
A1

array([0.3, 0.7, 1.1])

- 바로 이어서 활성화 함수에서의 처리 필요
- 가중치의 합 $a_1^{(1)}$을 $h()$시그모이드 함수에 따라 $z_1^{(1)}$로
![](image/fig 3-18.png)

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
Z1 = sigmoid(A1)

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


- 이어서 1층에서 2층으로 가는 과정
![](image/fig 3-19.png)

In [8]:
W2 = np.array([[0.1, .4], [.2, .5], [.3, .6]])
B2 = np.array([.1, .2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

(3,)
(3, 2)
(2,)


- 마지막 층에서도 동일한 구현 반복
- 단, 활성화 함수만 변경
![](image/fig 3-20.png)

In [9]:
def identity_function(x):
    return x

W3 = np.array([[.1, .3], [.2, .4]])
B3 = np.array([.1, .2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
Y

array([0.31682708, 0.69627909])

- 마지막 층에서는 항등함수로 (불필요하더라도) 출력값 구현
- 마지막 층의 활성화 함수는 $\sigma()$로 표시하여 은닉층의 활성화 함수 $h()$와는 다름을 명시
- 출력층 활성화 함수는 **풀고자 하는 문제의 성질에 맞게** 정의
- i.e. 회귀 - 항등함수, 2클래스 분류 - 시그모이드함수, 다중 분류 - 소프트맥스함수
___

### 3) 구현 정리